[sdksrv]
username = "root"
apikey = "xxxxxxxxxxxxxxxxxxxxxxx"

[smtp]
user = "aquariusye@163.com"
password = "xxxxxxyyy"
salt = "salt----------------"

[user]
maxuserfiles = 10

[session]
maxage = 7200
sessionkey = "session key ======"